checked code for matching SOLID principles and GRASP patterns, and ch…
GenesisEducationKyiv/hw1-se-school_2022-code-review-kathalie pull request #4
Opened 2022-09-18 15:39 UTC by kathalie

…anged type of case for constants

2022-09-20 17:08 UTC, damour requested changes

2022-09-20 17:08 UTC, damour commented on src/services/api/email-service.ts
> +        const currentRate = await new RateService().getRate();
Чому RateService() створюємо в методі, а не передаємо в конструкторі?

2022-09-20 21:18 UTC, kathalie commented on src/controllers/email-controller.ts
> +    constructor() {
слушно, виправлю). а чи потрібно сервіси закрити абстракцією, щоб контроллери не залежали від реалізації? тобто чи ок, якщо конструктор контроллеру отримує об'єкт конкретного класу (RateService, скажімо), а не реалізації інтерфейсу?

2022-09-20 21:23 UTC, kathalie commented on src/services/api/email-service.ts
> +        const currentRate = await new RateService().getRate();
вже зрозуміла, що краще передавати об'єкти параметрами у конструктор, аби собі ж не зв'язувати руки

2022-09-22 20:17 UTC, damour commented on src/controllers/email-controller.ts
> +    constructor() {
З теоретичної точки зору потрібно додавати інтерфейс. З практичної поки ти не пишеш юніт тести на контроллер або в тебе немає другої реалізацї сервісу, то можна і не виділяти.

2022-09-23 20:33 UTC, kathalie commented on src/controllers/email-controller.ts
> +    constructor() {
зрозуміла, дякую)

2022-09-30 19:48 UTC, damour approved these changes

2022-10-05 07:58 UTC, merged